# Generated by Django 3.2.6 on 2021-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.CreateModel(
            name='StartDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Начало стартапа',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('low_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('industry', models.ManyToManyField(related_name='all_industry', to='matching.Industry')),
                ('industry_prefer', models.ManyToManyField(related_name='prefer', to='matching.Industry')),
                ('stage', models.ManyToManyField(to='matching.StartDate')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
            },
        ),
    ]
