# Generated by Django 3.2.6 on 2021-08-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='high_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='low_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
