# Generated by Django 3.2.6 on 2021-08-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20210802_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('date_of_start', models.DateField()),
                ('info', models.TextField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.industry')),
            ],
            options={
                'verbose_name': 'Стартап',
                'verbose_name_plural': 'Стартапы',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.investor')),
                ('start_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.startup')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
