# Generated by Django 3.2.6 on 2021-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_mail_startup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startdate',
            options={'verbose_name': 'Начало стартапа', 'verbose_name_plural': 'Начало стартапа'},
        ),
        migrations.AddField(
            model_name='mail',
            name='sent_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
