# Generated by Django 3.2.6 on 2021-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20210802_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sent_date',
            field=models.DateField(),
        ),
    ]
