# Generated by Django 3.2.6 on 2021-08-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_alter_mail_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='date_of_start',
        ),
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.ManyToManyField(default=1, to='matching.StartDate'),
        ),
    ]
