# Generated by Django 3.2.6 on 2021-08-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20210804_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='stage',
        ),
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matching.startdate'),
        ),
    ]
