# Generated by Django 3.2.6 on 2021-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_alter_investor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='industry_prefer',
            field=models.BooleanField(default=False),
        ),
    ]
